

bank: main4.cpp account.cpp account.hpp checking_account.cpp checking_account.hpp savings_account.cpp savings_account.hpp
	g++ -Wall account.cpp main4.cpp checking_account.cpp savings_account.cpp -o bank
